"""
يُنشئ installer/Arabic.isl: نسخة مراجَعة لغوياً من ترجمة Inno Setup العربية (Languages\\Arabic.isl).
الترجمة الأصلية فيها أخطاء إملائية وهمزات خاطئة وصيغ عامية («جاري»، «إختر»، «تثبي»، «الخطء»).
التشغيل (عند تحديث Inno Setup):  python tools/make_arabic_isl.py
"""
import os
import re
import sys

SOURCE_CANDIDATES = [
    os.path.join(os.environ.get("ProgramFiles", r"C:\Program Files"), "Inno Setup 7", "Languages", "Arabic.isl"),
    os.path.join(os.environ.get("ProgramFiles(x86)", r"C:\Program Files (x86)"), "Inno Setup 6", "Languages", "Arabic.isl"),
]
TARGET = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "installer", "Arabic.isl")

FIXES = {
    "SetupLdrStartupMessage": "سيثبّت هذا المعالج %1. هل تريد المتابعة؟",
    "LdrCannotCreateTemp": "تعذّر إنشاء ملف مؤقت. أُلغي التثبيت",
    "LdrCannotExecTemp": "تعذّر تشغيل ملف من المجلد المؤقت. أُلغي التثبيت",
    "SetupFileMissing": "الملف %1 مفقود من مجلد التثبيت. يُرجى إصلاح المشكلة أو الحصول على نسخة جديدة من البرنامج.",
    "SetupFileCorrupt": "ملفات التثبيت تالفة. يُرجى الحصول على نسخة جديدة من البرنامج.",
    "SetupFileCorruptOrWrongVer": "ملفات التثبيت تالفة، أو غير متوافقة مع هذا الإصدار من معالج التثبيت. يُرجى إصلاح المشكلة أو الحصول على نسخة جديدة من البرنامج.",
    "InvalidParameter": "مُرِّر معامل غير صالح في سطر الأوامر:%n%n%1",
    "SetupAlreadyRunning": "معالج التثبيت قيد التشغيل بالفعل.",
    "WindowsVersionNotSupported": "لا يدعم هذا البرنامج إصدار ويندوز المثبت على جهازك.",
    "WindowsServicePackRequired": "يتطلب هذا البرنامج %1 حزمة الخدمة %2 أو أحدث.",
    "NotOnThisPlatform": "لا يعمل هذا البرنامج على %1.",
    "OnlyOnThisPlatform": "يجب تشغيل هذا البرنامج على %1.",
    "OnlyOnTheseArchitectures": "لا يمكن تثبيت هذا البرنامج إلا على إصدارات ويندوز المصممة لمعماريات المعالجات التالية:%n%n%1",
    "WinVersionTooLowError": "يتطلب هذا البرنامج %1 الإصدار %2 أو أحدث.",
    "WinVersionTooHighError": "لا يمكن تثبيت هذا البرنامج على %1 الإصدار %2 أو أحدث.",
    "AdminPrivilegesRequired": "يجب تسجيل الدخول بحساب مسؤول لتثبيت هذا البرنامج.",
    "PowerUserPrivilegesRequired": "يجب تسجيل الدخول بحساب مسؤول أو بحساب عضو في مجموعة المستخدمين المتميزين لتثبيت هذا البرنامج.",
    "SetupAppRunningError": "اكتشف معالج التثبيت أن %1 قيد التشغيل حالياً.%n%nيُرجى إغلاقه الآن، ثم الضغط على «موافق» للمتابعة، أو «إلغاء الأمر» للخروج.",
    "UninstallAppRunningError": "اكتشف معالج الإزالة أن %1 قيد التشغيل حالياً.%n%nيُرجى إغلاقه الآن، ثم الضغط على «موافق» للمتابعة، أو «إلغاء الأمر» للخروج.",
    "PrivilegesRequiredOverrideText1": "يمكن تثبيت %1 لجميع المستخدمين (يتطلب صلاحيات المسؤول)، أو في حسابك فقط.",
    "PrivilegesRequiredOverrideText2": "يمكن تثبيت %1 في حسابك فقط، أو لجميع المستخدمين (يتطلب صلاحيات المسؤول).",
    "PrivilegesRequiredOverrideAllUsers": "التثبيت لـ&جميع المستخدمين",
    "PrivilegesRequiredOverrideAllUsersRecommended": "التثبيت لـ&جميع المستخدمين (مستحسن)",
    "PrivilegesRequiredOverrideCurrentUser": "التثبيت في حسابي &فقط",
    "PrivilegesRequiredOverrideCurrentUserRecommended": "التثبيت في حسابي &فقط (مستحسن)",
    "ErrorCreatingDir": "تعذّر على معالج التثبيت إنشاء المجلد «%1»",
    "ErrorTooManyFilesInDir": "تعذّر إنشاء ملف في المجلد «%1» لأنه يحتوي على عدد كبير جداً من الملفات",
    "ExitSetupMessage": "لم يكتمل التثبيت. إذا خرجت الآن فلن يُثبَّت البرنامج.%n%nيمكنك تشغيل معالج التثبيت مرة أخرى لاحقاً لإكمال التثبيت.%n%nهل تريد الخروج من معالج التثبيت؟",
    "AboutSetupMenuItem": "&حول معالج التثبيت...",
    "AboutSetupTitle": "حول معالج التثبيت",
    "AboutSetupMessage": "%1 الإصدار %2%n%3%n%nموقع %1 على الإنترنت:%n%4",
    "TranslatorNote": "الترجمة العربية: ناصر بعزيز، مع مراجعة لغوية من فريق Omnya للبرمجيات",
    "ButtonOK": "موافق",
    "SelectLanguageTitle": "اختيار لغة التثبيت",
    "SelectLanguageLabel": "اختر اللغة التي تريد استخدامها أثناء التثبيت. وسيعمل البرنامج باللغة نفسها.",
    "ClickNext": "اضغط «التالي» للمتابعة، أو «إلغاء الأمر» للخروج من معالج التثبيت.",
    "BrowseDialogTitle": "استعراض المجلدات",
    "BrowseDialogLabel": "اختر مجلداً من القائمة التالية، ثم اضغط «موافق».",
    "WelcomeLabel1": "مرحباً بك في معالج تثبيت [name]",
    "WelcomeLabel2": "سيثبّت هذا المعالج [name/ver] على جهازك.%n%nيُستحسن إغلاق جميع التطبيقات الأخرى قبل المتابعة.",
    "PasswordLabel3": "يُرجى إدخال كلمة المرور، ثم الضغط على «التالي» للمتابعة. كلمات المرور تميّز بين الأحرف الكبيرة والصغيرة.",
    "LicenseLabel": "يُرجى قراءة المعلومات المهمة التالية قبل المتابعة.",
    "LicenseLabel3": "يُرجى قراءة اتفاقية الترخيص التالية. يجب الموافقة على شروطها قبل متابعة التثبيت.",
    "LicenseAccepted": "قرأت الاتفاقية، و&أوافق على شروطها",
    "LicenseNotAccepted": "&لا أوافق على الاتفاقية",
    "InfoBeforeLabel": "يُرجى قراءة المعلومات المهمة التالية قبل المتابعة.",
    "InfoBeforeClickLabel": "عندما تكون مستعداً لمتابعة التثبيت، اضغط «التالي».",
    "InfoAfterLabel": "يُرجى قراءة المعلومات المهمة التالية قبل المتابعة.",
    "InfoAfterClickLabel": "عندما تكون مستعداً للمتابعة، اضغط «التالي».",
    "UserInfoDesc": "يُرجى إدخال بياناتك.",
    "UserInfoName": "اسم ال&مستخدم:",
    "UserInfoNameRequired": "يجب إدخال اسم.",
    "WizardSelectDir": "اختيار مجلد التثبيت",
    "SelectDirDesc": "أين تريد تثبيت [name]؟",
    "SelectDirLabel3": "سيثبّت المعالج [name] في المجلد التالي.",
    "SelectDirBrowseLabel": "للمتابعة اضغط «التالي». وإذا أردت اختيار مجلد آخر، فاضغط «استعراض».",
    "DiskSpaceGBLabel": "يلزم [gb] جيجابايت على الأقل من المساحة الفارغة.",
    "DiskSpaceMBLabel": "يلزم [mb] ميجابايت على الأقل من المساحة الفارغة.",
    "CannotInstallToNetworkDrive": "لا يمكن التثبيت على محرك أقراص شبكي.",
    "CannotInstallToUNCPath": "لا يمكن التثبيت على مسار شبكي (UNC).",
    "InvalidPath": "يجب إدخال مسار كامل يبدأ بحرف محرك الأقراص، مثل:%n%nC:\\APP%n%nأو مسار شبكي بالصيغة:%n%n\\\\server\\share",
    "InvalidDrive": "محرك الأقراص أو المسار الشبكي الذي اخترته غير موجود أو يتعذّر الوصول إليه. يُرجى اختيار غيره.",
    "DiskSpaceWarning": "يحتاج التثبيت إلى %1 كيلوبايت على الأقل من المساحة الفارغة، والمتاح على محرك الأقراص المحدد %2 كيلوبايت فقط.%n%nهل تريد المتابعة على أي حال؟",
    "BadDirName32": "لا يمكن أن يحتوي اسم المجلد على أي من الأحرف التالية:%n%n%1",
    "DirExists": "المجلد:%n%n%1%n%nموجود بالفعل. هل تريد التثبيت فيه على أي حال؟",
    "DirDoesntExist": "المجلد:%n%n%1%n%nغير موجود. هل تريد إنشاءه؟",
    "WizardSelectComponents": "اختيار المكونات",
    "SelectComponentsDesc": "ما المكونات التي تريد تثبيتها؟",
    "SelectComponentsLabel2": "اختر المكونات التي تريد تثبيتها، وألغِ اختيار المكونات التي لا تريدها. ثم اضغط «التالي» للمتابعة.",
    "NoUninstallWarning": "اكتشف معالج التثبيت أن المكونات التالية مثبتة على جهازك بالفعل:%n%n%1%n%nإلغاء اختيارها لن يزيلها.%n%nهل تريد المتابعة على أي حال؟",
    "ComponentsDiskSpaceGBLabel": "يتطلب الاختيار الحالي [gb] جيجابايت على الأقل من المساحة الفارغة.",
    "ComponentsDiskSpaceMBLabel": "يتطلب الاختيار الحالي [mb] ميجابايت على الأقل من المساحة الفارغة.",
    "WizardSelectTasks": "اختيار المهام الإضافية",
    "SelectTasksDesc": "ما المهام الإضافية التي تريد تنفيذها؟",
    "SelectTasksLabel2": "اختر المهام الإضافية التي تريد أن ينفّذها المعالج أثناء تثبيت [name]، ثم اضغط «التالي».",
    "WizardSelectProgramGroup": "اختيار مجلد قائمة ابدأ",
    "SelectStartMenuFolderDesc": "أين تريد وضع اختصارات البرنامج؟",
    "SelectStartMenuFolderLabel3": "سينشئ المعالج اختصارات البرنامج في مجلد قائمة ابدأ التالي.",
    "SelectStartMenuFolderBrowseLabel": "للمتابعة اضغط «التالي». وإذا أردت اختيار مجلد آخر، فاضغط «استعراض».",
    "BadGroupName": "لا يمكن أن يحتوي اسم المجلد على أي من الأحرف التالية:%n%n%1",
    "ReadyLabel1": "المعالج جاهز الآن لبدء تثبيت [name] على جهازك.",
    "ReadyLabel2a": "اضغط «تثبيت» للمتابعة، أو «السابق» لمراجعة الإعدادات أو تغييرها.",
    "ReadyLabel2b": "اضغط «تثبيت» للمتابعة.",
    "ReadyMemoDir": "مجلد التثبيت:",
    "ReadyMemoType": "نوع التثبيت:",
    "ReadyMemoTasks": "المهام الإضافية:",
    "DownloadingLabel2": "جارٍ تنزيل الملفات الإضافية...",
    "ButtonStopDownload": "إ&يقاف التنزيل",
    "StopDownload": "هل تريد إيقاف التنزيل؟",
    "ErrorDownloadAborted": "أُلغي التنزيل",
    "ErrorDownloadFailed": "فشل التنزيل: %1 %2",
    "ExtractingLabel": "جارٍ فك ضغط الملفات الإضافية...",
    "StopExtraction": "هل تريد إيقاف فك الضغط؟",
    "ErrorExtractionAborted": "أُوقف فك الضغط",
    "ArchiveIncorrectPassword": "كلمة المرور غير صحيحة",
    "PreparingDesc": "يستعد المعالج لتثبيت [name] على جهازك.",
    "PreviousInstallNotCompleted": "لم يكتمل تثبيت برنامج سابق أو إزالته، ويلزم إعادة تشغيل الجهاز لإكماله.%n%nبعد إعادة التشغيل، شغّل معالج التثبيت مرة أخرى لإكمال تثبيت [name].",
    "CannotContinue": "لا يمكن متابعة التثبيت. يُرجى الضغط على «إلغاء الأمر» للخروج.",
    "ApplicationsFound": "التطبيقات التالية تستخدم ملفات يجب أن يحدّثها معالج التثبيت. يُستحسن السماح للمعالج بإغلاقها تلقائياً.",
    "ApplicationsFound2": "التطبيقات التالية تستخدم ملفات يجب أن يحدّثها معالج التثبيت. يُستحسن السماح للمعالج بإغلاقها تلقائياً، وسيحاول إعادة تشغيلها بعد اكتمال التثبيت.",
    "CloseApplications": "إغلاق التطبيقات &تلقائياً",
    "DontCloseApplications": "&عدم إغلاق التطبيقات",
    "ErrorCloseApplications": "تعذّر على المعالج إغلاق جميع التطبيقات تلقائياً. يُستحسن إغلاق التطبيقات التي تستخدم الملفات المطلوب تحديثها قبل المتابعة.",
    "PrepareToInstallNeedsRestart": "يجب إعادة تشغيل الجهاز. بعد إعادة التشغيل، شغّل معالج التثبيت مرة أخرى لإكمال تثبيت [name].%n%nهل تريد إعادة التشغيل الآن؟",
    "WizardInstalling": "جارٍ التثبيت",
    "InstallingLabel": "يُرجى الانتظار حتى يُكمل المعالج تثبيت [name] على جهازك.",
    "FinishedHeadingLabel": "اكتمل تثبيت [name]",
    "FinishedLabelNoIcons": "أكمل المعالج تثبيت [name] على جهازك.",
    "FinishedLabel": "أكمل المعالج تثبيت [name] على جهازك. ويمكنك تشغيل البرنامج من الاختصارات التي أُنشئت.",
    "ClickFinish": "اضغط «إنهاء» للخروج من معالج التثبيت.",
    "FinishedRestartLabel": "لإكمال تثبيت [name] يجب إعادة تشغيل الجهاز. هل تريد إعادة التشغيل الآن؟",
    "FinishedRestartMessage": "لإكمال تثبيت [name] يجب إعادة تشغيل الجهاز.%n%nهل تريد إعادة التشغيل الآن؟",
    "ShowReadmeCheck": "نعم، أريد عرض ملف «اقرأني»",
    "YesRadio": "&نعم، أعد تشغيل الجهاز الآن",
    "NoRadio": "&لا، سأعيد تشغيل الجهاز لاحقاً",
    "SelectDiskLabel2": "يُرجى إدخال القرص %1 ثم الضغط على «موافق».%n%nإذا كانت ملفات هذا القرص في مجلد غير المجلد الظاهر أدناه، فأدخل المسار الصحيح أو اضغط «استعراض».",
    "PathLabel": "ال&مسار:",
    "FileNotInDir2": "تعذّر العثور على الملف «%1» في «%2». يُرجى إدخال القرص الصحيح أو اختيار مجلد آخر.",
    "SelectDirectoryLabel": "يُرجى تحديد موقع القرص التالي.",
    "SetupAborted": "لم يكتمل التثبيت.%n%nيُرجى إصلاح المشكلة ثم تشغيل معالج التثبيت مرة أخرى.",
    "AbortRetryIgnoreSelectAction": "اختر إجراءً",
    "AbortRetryIgnoreRetry": "إعادة ال&محاولة",
    "RetryCancelSelectAction": "اختر إجراءً",
    "RetryCancelRetry": "إعادة ال&محاولة",
    "RetryCancelCancel": "إلغاء الأمر",
    "StatusClosingApplications": "جارٍ إغلاق التطبيقات...",
    "StatusCreateDirs": "جارٍ إنشاء المجلدات...",
    "StatusExtractFiles": "جارٍ استخراج الملفات...",
    "StatusDownloadFiles": "جارٍ تنزيل الملفات...",
    "StatusCreateIcons": "جارٍ إنشاء الاختصارات...",
    "StatusCreateIniEntries": "جارٍ إنشاء مدخلات INI...",
    "StatusCreateRegistryEntries": "جارٍ إنشاء مفاتيح السجل...",
    "StatusRegisterFiles": "جارٍ تسجيل الملفات...",
    "StatusSavingUninstall": "جارٍ حفظ معلومات الإزالة...",
    "StatusRunProgram": "جارٍ إنهاء التثبيت...",
    "StatusRestartingApplications": "جارٍ إعادة تشغيل التطبيقات...",
    "StatusRollback": "جارٍ التراجع عن التغييرات...",
    "ErrorFunctionFailed": "فشل %1، رمز الخطأ %2",
    "ErrorFunctionFailedWithMessage": "فشل %1، رمز الخطأ %2.%n%3",
    "ErrorExecutingProgram": "تعذّر تشغيل الملف:%n%1",
    "ErrorRegOpenKey": "خطأ في فتح مفتاح السجل:%n%1\\%2",
    "ErrorRegCreateKey": "خطأ في إنشاء مفتاح السجل:%n%1\\%2",
    "ErrorRegWriteKey": "خطأ في الكتابة إلى مفتاح السجل:%n%1\\%2",
    "FileAbortRetryIgnoreSkipNotRecommended": "&تخطي هذا الملف (غير مستحسن)",
    "ExistingFileReadOnly2": "تعذّر استبدال الملف الموجود لأنه للقراءة فقط.",
    "ExistingFileReadOnlyRetry": "إ&زالة خاصية القراءة فقط ثم إعادة المحاولة",
    "ExistingFileReadOnlyKeepExisting": "الا&حتفاظ بالملف الموجود",
    "FileExistsSelectAction": "اختر إجراءً",
    "FileExistsKeepExisting": "الا&حتفاظ بالملف الموجود",
    "FileExistsOverwriteOrKeepAll": "تطبيق هذا الاختيار على التعارضات ال&تالية",
    "ExistingFileNewerSelectAction": "اختر إجراءً",
    "ExistingFileNewer2": "الملف الموجود أحدث من الملف الذي سيثبّته المعالج.",
    "ExistingFileNewerKeepExisting": "الا&حتفاظ بالملف الموجود (مستحسن)",
    "ExistingFileNewerOverwriteOrKeepAll": "تطبيق هذا الاختيار على التعارضات ال&تالية",
    "ErrorCreatingTemp": "حدث خطأ أثناء إنشاء ملف في مجلد التثبيت:",
    "ErrorReadingSource": "حدث خطأ أثناء قراءة ملف المصدر:",
    "ErrorCopying": "حدث خطأ أثناء نسخ ملف:",
    "ErrorDownloading": "حدث خطأ أثناء تنزيل ملف:",
    "ErrorExtracting": "حدث خطأ أثناء استخراج ملفات من الأرشيف:",
    "ErrorReplacingExistingFile": "حدث خطأ أثناء استبدال الملف الموجود:",
    "ErrorRestartReplace": "فشل الاستبدال عند إعادة التشغيل:",
    "ErrorRenamingTemp": "حدث خطأ أثناء إعادة تسمية ملف في مجلد التثبيت:",
    "ErrorRegSvr32Failed": "فشل RegSvr32 برمز الخروج %1",
    "ErrorRegisterTypeLib": "تعذّر تسجيل مكتبة الأنواع: %1",
    "UninstallDisplayNameMarkAllUsers": "جميع المستخدمين",
    "ErrorOpeningReadme": "حدث خطأ أثناء فتح ملف «اقرأني».",
    "ErrorRestartingComputer": "تعذّر على المعالج إعادة تشغيل الجهاز. يُرجى إعادة تشغيله يدوياً.",
    "UninstallNotFound": "الملف «%1» غير موجود. تتعذّر الإزالة.",
    "UninstallOpenError": "تعذّر فتح الملف «%1». تتعذّر الإزالة",
    "UninstallUnsupportedVer": "صيغة سجل الإزالة «%1» لا يتعرّف عليها هذا الإصدار من برنامج الإزالة. تتعذّر الإزالة",
    "UninstallUnknownEntry": "وُجد إدخال غير معروف (%1) في سجل الإزالة",
    "ConfirmUninstall": "هل تريد إزالة %1 وجميع مكوناته بالكامل؟",
    "UninstallOnlyOnWin64": "لا يمكن إزالة هذا البرنامج إلا على إصدار ويندوز 64 بت.",
    "OnlyAdminCanUninstall": "لا يمكن إزالة هذا البرنامج إلا بحساب له صلاحيات المسؤول.",
    "UninstallStatusLabel": "يُرجى الانتظار حتى تكتمل إزالة %1 من جهازك.",
    "UninstalledAll": "أُزيل %1 من جهازك بنجاح.",
    "UninstalledMost": "اكتملت إزالة %1.%n%nتعذّرت إزالة بعض العناصر، ويمكنك حذفها يدوياً.",
    "UninstalledAndNeedsRestart": "لإكمال إزالة %1 يجب إعادة تشغيل الجهاز.%n%nهل تريد إعادة التشغيل الآن؟",
    "UninstallDataCorrupted": "الملف «%1» تالف. تتعذّر الإزالة",
    "ConfirmDeleteSharedFile2": "يشير النظام إلى أن الملف المشترك التالي لم يعد يستخدمه أي برنامج. هل تريد حذفه؟%n%nإذا كانت هناك برامج ما زالت تستخدمه، فقد لا تعمل بشكل صحيح بعد حذفه. إذا لم تكن متأكداً فاختر «لا»؛ فبقاء الملف على جهازك لا يسبب أي ضرر.",
    "WizardUninstalling": "حالة الإزالة",
    "StatusUninstalling": "جارٍ إزالة %1...",
    "ShutdownBlockReasonInstallingApp": "جارٍ تثبيت %1.",
    "ShutdownBlockReasonUninstallingApp": "جارٍ إزالة %1.",
    # [CustomMessages]
    "CreateDesktopIcon": "إنشاء اختصار على سطح المكتب",
    "CreateQuickLaunchIcon": "إنشاء اختصار في شريط «التشغيل السريع»",
    "ProgramOnTheWeb": "موقع %1 على الإنترنت",
    "UninstallProgram": "إزالة %1",
    "AssocFileExtension": "ربط %1 بامتداد الملفات %2",
    "AssocingFileExtension": "جارٍ ربط %1 بامتداد الملفات %2...",
    "AutoStartProgramGroupDescription": "بدء التشغيل:",
    "AutoStartProgram": "تشغيل %1 تلقائياً",
    "AddonHostProgramNotFound": "تعذّر العثور على %1 في المجلد الذي اخترته.%n%nهل تريد المتابعة على أي حال؟",
}


def main():
    source = next((p for p in SOURCE_CANDIDATES if os.path.isfile(p)), None)
    if not source:
        sys.exit("Arabic.isl was not found in the Inno Setup installation")
    with open(source, encoding="utf-8-sig") as f:
        lines = f.read().splitlines()
    pending = dict(FIXES)
    out = []
    for line in lines:
        m = re.match(r"^([A-Za-z0-9]+)=", line)
        if m and m.group(1) in pending:
            line = f"{m.group(1)}={pending.pop(m.group(1))}"
        out.append(line)
    if pending:
        sys.exit(f"Keys not found in {source}: {', '.join(pending)}")
    header = ["; نسخة مراجَعة لغوياً من ترجمة Inno Setup العربية. أنشأها tools/make_arabic_isl.py، فلا تعدّلها يدوياً", ""]
    with open(TARGET, "w", encoding="utf-8-sig", newline="\r\n") as f:
        f.write("\n".join(header + out) + "\n")
    print(f"{TARGET}: {len(FIXES)} messages reviewed")


if __name__ == "__main__":
    main()
